name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUYGKYRQC3B53TLZL
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip
          unzip terraform_1.1.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Initialize Terraform
        run: |
          mkdir infrastructure
          cd infrastructure
          terraform init

      - name: Plan Terraform
        id: terraform-plan
        run: |
          cd infrastructure
          terraform plan -out=tfplan
        continue-on-error: true

      - name: Deploy Terraform
        if: steps.terraform-plan.outputs.exit-code == 0
        run: |
          cd infrastructure
          terraform apply 

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: my-aws-registry/my-app:${{ github.sha }}

      - name: Deploy Docker container to ECS
        run: |
          aws ecs update-service \
            --cluster killer4 \
            --service my-ecs-service \
            --force-new-deployment \
            --region us-east-1
