name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
steps:
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v1
  - name: Terraform Init
    run: terraform init
    working-directory: ./terraform
  - name: Terraform Apply
    run: terraform apply -auto-approve
    working-directory: ./terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ AKIAUYGKYRQC3B53TLZL }}
      AWS_SECRET_ACCESS_KEY: ${{ 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 }}
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
    with:
      registry: 326842747909.dkr.ecr.US East.amazonaws.com
  - name: Build and Push Docker Image
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: 326842747909.dkr.ecr.US East.amazonaws.com/killer2021:latest
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: <repository_name>
      AWS_ACCESS_KEY_ID: ${{ AKIAUYGKYRQC3B53TLZL }}
      AWS_SECRET_ACCESS_KEY: ${{ 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 }}
