name: Deploy Demo App

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_NAME: demo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Terraform apply
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIAUYGKYRQC3B53TLZL }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
          AWS_DEFAULT_REGION: ${{ us-east-1 }}
        run: |
          terraform init
          terraform apply --auto-approve

      - name: Verify deployment
        run: |
          # Check ECS service status
          # Access demo app URL
